### ISSUE TITLE
Convert project to use TS

### ISSUE THREAD

**Issue by vijayxtreme** [team-hack/stockapp#21]
Would be really good to jump on TS as early as possible with this.  Spend some time researching the syntax and let's see if we can pair program later (on weekend or nights after work) to hash it all out.

**Comment by Schraut** [comment]
Ok for sure. Saturday works best for me.

**Comment by vijayxtreme** [comment]
Sounds good -- can you send me an invite (via calendar). Just use my vijay@javascriptla.net one, and I'll work with the time you suggest.

**Comment by vijayxtreme** [comment]
Also just adding this here for reference: https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started

**Comment by Schraut** [comment]
Sounds good! Invitation sent. Let me know if you need to change anything.

**Comment by vijayxtreme** [comment]
Project is now in TypeScript :)
